import { Manrope } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import SiteHeader from "@/components/SiteHeader";

const manrope = Manrope({
  subsets: ["latin"], // Specify subsets
  variable: "--font-manrope", // Set CSS variable
  weight: ["200", "300", "400", "500", "600", "700", "800"], // Define weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        <SiteHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
